### ISSUE TITLE
EfCoreSelect

### ISSUE THREAD

**Issue by TomatorCZ** [paillave/Etl.Net#313]
Hi,

is there a way how to use the select using batches without loading all data at once from a server into memory?

**Comment by paillave** [comment]
Hello, 
The very point of ETL is not to load everything into memory.
Nevertheless, like every ETL on the market, some operations actually need to load every in memory to be able to accomplish their purpose. For instance, the sort operation needs to have to whole content of the stream before being able to issue the first element to the listening operator. If you want to know if the ETL you define will consume memory, you want to see the estimated execution plan like mentioned here: https://paillave.github.io/Etl.Net/docs/tutorials/trackAndCheck.
The estimated execution plan mention for each operator the forecasted impact for the memory and the processor. An impact of 3 for the memory means that the operator need to load one of the input stream in memory. An impact of 1 for the memory means that no record will be stored in memory; it will just be processed and transmitted to the next operator. An impact of 2 means that just a subset of records will be stored in memory.
Hope this helps.

**Comment by paillave** [comment]
My mistake, I appears there is a possibility not to load the full result in memory, as mentioned here: https://docs.microsoft.com/en-us/ef/core/performance/efficient-querying#buffering-and-streaming

I will definitely work on this very soon.
Stay tuned!

**Comment by paillave** [comment]
Use the version  2.0.22-beta (checking "prerelease" in visual studio). FYI it works with NET6.
Now, `EfCoreSelect` has a second optional parameter called `streamMode`.
Set it to true if you dan't want to load the whole dataset in memory before submitting values to the process.
The reason why it is switchable is because EF cannot be used simultatenously on different threads; it raises an exception if 2 threads are using it simultaneously. As ETL.NET does process source streams in a multi thread mode; EF Core extension for ETL.NET ensures that any use it makes of the dbcontext is exclusive. By default, it will load the whole dataset in memory before submitting values one by one to the rest of the process. 
If the dataset is not too big, the lock set on the dbcontext is released after a short amount of time, and the rest of the process can use the dbcontext without waiting for too long. 
If the dataset is very big, it is better indeed to switch to the stream mode. The dbcontext will be locked from other use within etl.net as long as not every record is pushed to the stream. If some other parallel operators need to use the dbcontext, they will have to wait... and connot do anything but buffer their incoming rows into memory as they can't process it yet.
I hope I am clear.
Let me know if any issue.
