### ISSUE TITLE
EF Core Spatial Integration

### ISSUE THREAD

**Issue by mbanks9** [paillave/Etl.Net#429]
Do you currently allow for spatial joins / lookups as part of the ETL process pipeline? And if not, are you considering support for it?

**Comment by paillave** [comment]
I will give it a look.
Can you give me an example of code you would like to work to achieve the data process you have in mind? This will help me greatly.

**Comment by paillave** [comment]
It appears that if you use entity framework, you can put your spacial data into the dedicated type like described [here](https://learn.microsoft.com/en-us/ef/core/modeling/spatial). 

For example, for a point of a map, use the type `NetTopologySuite.Geometries.Point`. Then you can make a join or a lookup like described [here](https://paillave.github.io/Etl.Net/docs/recipes/linkStreams#join-and-leftjoin) since this type is an `IComparable`. Note that most of type of this library implement `IComparable` making them working with a `lookup` or a `Join`.

**Comment by mbanks9** [comment]
Okay, that answers my question. I do have one more but it's unrelated to my initial one.

Is there a way to use a custom comparer when using the stream's group by operator? I want to group very close numbers (not exactly the same) into a single record.

**Comment by paillave** [comment]
using the `Select` operator, you will have to add a property of a type that you will build that will wrap this value. This type has to be usable as a key of a dictionary. Example if we suppose that the value you want to group on its approximation is a double: 

```csharp
public struct MyApproximativeType:IComparable<MyApproximativeType>, IEquatable<MyApproximativeType>
{
    private readonly int _roundedValue;
    public MyApproximativeType(double value)
    {
        _roundedValue=(10)Math.Round(value/13); //this computation is a way to "round" a value.
    }
    public int CompareTo (MyApproximativeType? other)
    {
        if(other == null) return 1;
        return _roundedValue.CompareTo(other._roundedValue);
    }
    public bool Equals (T? other)
    {
        if(other == null) return false;
        return _roundedValue.Equals(other._roundedValue);
    }
    public override GetHash()
    {
        return _roundedValue.GetHash();
    }
}
```

NOTE: this was "coded" as I was writting this very answer, so don't take it for granted; it is just to give the idea of what should be done. It will certainly not wortk as is.
